import React, { createContext, useContext, useState, useEffect } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";

type Language = "uz" | "ru" | "en";

const translations: Record<Language, Record<string, string>> = {
  uz: {
    "app.name": "FitBoom",
    "nav.home": "Asosiy",
    "nav.gyms": "Zallar",
    "nav.map": "Xarita",
    "nav.bookings": "Bronlar",
    "nav.profile": "Profil",
    "nav.scanner": "Skaner",
    "nav.classes": "Video darslar",
    "auth.title": "FitBoom ga xush kelibsiz",
    "auth.subtitle": "Sport hayotingizni boshqaring",
    "auth.phone_label": "Telefon raqami",
    "auth.phone_placeholder": "+998901234567",
    "auth.send_code": "Kod yuborish",
    "auth.sending": "Yuborilmoqda...",
    "auth.code_label": "Tasdiqlash kodi",
    "auth.code_placeholder": "6 xonali kod",
    "auth.verify": "Tasdiqlash",
    "auth.verifying": "Tekshirilmoqda...",
    "auth.code_sent": "Kod yuborildi",
    "auth.resend": "Qayta yuborish",
    "auth.back": "Orqaga",
    "profile.complete_title": "Profilni to'ldiring",
    "profile.complete_subtitle": "Davom etish uchun ma'lumotlaringizni kiriting",
    "profile.name": "Ism",
    "profile.name_placeholder": "Ismingizni kiriting",
    "profile.age": "Yosh",
    "profile.age_placeholder": "Yoshingizni kiriting",
    "profile.gender": "Jins",
    "profile.male": "Erkak",
    "profile.female": "Ayol",
    "profile.save": "Saqlash",
    "profile.saving": "Saqlanmoqda...",
    "profile.title": "Profil",
    "profile.credits": "kredit",
    "profile.edit": "Tahrirlash",
    "profile.logout": "Chiqish",
    "profile.admin": "Admin panel",
    "profile.gym_owner": "Zal egasi paneli",
    "profile.settings": "Sozlamalar",
    "profile.language": "Til",
    "profile.expires": "Muddat tugaydi",
    "profile.days_left": "kun qoldi",
    "profile.credits_title": "Kredit balansi",
    "profile.credits_count": "kredit",
    "profile.topup": "To'ldirish",
    "profile.expired_message": "Muddat tugadi! Yangilang",
    "profile.renew": "Yangilash",
    "profile.expiring_soon": "Diqqat:",
    "profile.credit_history": "Kredit tarixi",
    "profile.topup_history": "To'ldirish tarixi",
    "profile.no_credit_history": "Kredit tarixi mavjud emas",
    "profile.no_topup_history": "To'ldirish tarixi mavjud emas",
    "profile.expired_badge": "Muddat tugadi!",
    "home.welcome": "Xush kelibsiz",
    "home.balance": "Kredit balansi",
    "home.topup": "To'ldirish",
    "home.near_gyms": "Sizga eng yaqin zallar",
    "home.my_bookings": "Mening bronlarim",
    "home.no_bookings": "Faol bron yo'q",
    "home.view_all": "Barchasini ko'rish",
    "home.upcoming": "Kelayotgan bronlar",
    "home.subtitle": "Sport hayotingizni boshqaring",
    "home.sorted_by_distance": "Masofaga qarab saralangan",
    "home.days_left": "kun qoldi",
    "home.expired": "Muddati o'tgan",
    "home.renew": "Yangilash",
    "home.scanner_desc": "Tez orada bu funksiya ishga tushadi. QR-kodni skanerlash orqali sport zaliga kirishingiz mumkin bo'ladi.",
    "gyms.title": "Sport Zallar",
    "gyms.search": "Zal qidirish...",
    "gyms.all": "Hammasi",
    "gyms.no_results": "Zallar topilmadi",
    "gyms.credits": "kredit",
    "gym.book": "Bron qilish",
    "gym.book_now": "Hozir bron qilish",
    "gym.slots": "Vaqt slotlari",
    "gym.no_slots": "Bugun vaqt sloti yo'q",
    "gym.select_slot": "Vaqt tanlang",
    "gym.select_date": "Sana tanlang",
    "gym.confirm_booking": "Bronni tasdiqlash",
    "gym.credits_needed": "kredit kerak",
    "gym.not_enough": "Kredit yetarli emas",
    "gym.booked": "Bron qilindi!",
    "gym.facilities": "Imkoniyatlar",
    "gym.hours": "Ish vaqti",
    "gym.address": "Manzil",
    "gym.rating": "Reyting",
    "gym.open_maps": "Xaritada ko'rish",
    "map.title": "Zallar xaritasi",
    "map.locate_me": "Mening joylashuvim",
    "bookings.title": "Bronlar",
    "bookings.upcoming": "Kelayotgan",
    "bookings.past": "O'tgan",
    "bookings.no_upcoming": "Kelayotgan bron yo'q",
    "bookings.no_past": "O'tgan bron yo'q",
    "bookings.cancel": "Bekor qilish",
    "bookings.show_qr": "QR Kodini ko'rsatish",
    "bookings.cancelled": "Bekor qilindi",
    "bookings.credits_returned": "Kredit qaytarildi",
    "bookings.status_pending": "Kutilmoqda",
    "bookings.status_completed": "Tashrif buyurildi",
    "bookings.status_missed": "Kelmadi",
    "bookings.status_cancelled": "Bekor qilindi",
    "bookings.status_unknown": "Noma'lum",
    "bookings.tab_upcoming": "Kelayotgan",
    "bookings.tab_past": "O'tgan",
    "bookings.empty_upcoming": "Hozircha faol bronlar yo'q",
    "bookings.empty_past": "O'tgan bronlar yo'q",
    "bookings.gym_default": "Sport zal",
    "bookings.scanner_btn": "Skaner",
    "bookings.cancel_confirm": "Bekor qilasizmi?",
    "bookings.cancel_no": "Yo'q",
    "bookings.cancel_yes": "Ha, bekor qilish",
    "bookings.within_2h_warning": "2 soatdan kam qoldi — bekor qilsangiz kredit qaytarilmaydi",
    "bookings.cancel_2h_title": "⚠️ Diqqat!",
    "bookings.cancel_2h_msg": "Boshlanishiga 2 soatdan kam qoldi. Bekor qilsangiz kredit qaytarilmaydi. Baribir bekor qilasizmi?",
    "bookings.cancel_stay": "Yo'q, qoldiraman",
    "bookings.cancel_do": "Ha, bekor qilish",
    "bookings.cancel_success": "Muvaffaqiyatli!",
    "bookings.cancel_no_refund": "Bron bekor qilindi. Boshlanishiga 2 soatdan kam qolganligi sababli kredit qaytarilmadi.",
    "bookings.cancel_base_msg": "Bron bekor qilindi.",
    "bookings.cancel_refund_suffix": " kredit hisobingizga qaytarildi.",
    "bookings.error_no_id": "Bron ID topilmadi",
    "bookings.session_expired": "Sessiya tugadi. Qayta tizimga kiring.",
    "bookings.cancel_error": "Bronni bekor qilishda xatolik yuz berdi",
    "scanner.title": "QR Skaner",
    "scanner.desc": "Zal QR kodini skaner qiling",
    "scanner.scanning": "Skanerlash...",
    "scanner.success": "Kirish tasdiqlandi!",
    "scanner.permission_title": "Kameraga ruxsat kerak",
    "scanner.permission_desc": "QR kodni skanerlash uchun kameraga ruxsat bering",
    "scanner.permission_denied": "Kamera ruxsati rad etilgan. Qurilma sozlamalaridan kameraga ruxsat bering.",
    "scanner.grant": "Ruxsat berish",
    "scanner.open_settings": "Sozlamalarga o'tish",
    "scanner.ticket_title": "KIRISH TASDIQLANDI",
    "scanner.time_label": "Vaqt",
    "scanner.date_label": "Sana",
    "scanner.show_admin": "Shu ekranni administratorga ko'rsating",
    "scanner.rescan": "Qayta skanerlash",
    "scanner.back_bookings": "Bronlarga qaytish",
    "scanner.checking": "Tekshirilmoqda...",
    "scanner.hint": "Har bir zal eshigida QR kod bor. Shu QR ni skanerlang.",
    "scanner.frame_hint": "Zal eshigidagi QR kodni ramka ichiga joylashtiring",
    "scanner.not_fitboom_qr": "Bu FitBoom QR kodi emas",
    "scanner.not_gym_qr": "Bu FitBoom zal QR kodi emas",
    "scanner.error_generic": "Xatolik yuz berdi",
    "scanner.welcome_default": "ga xush kelibsiz!",
    "courses.title": "Video Kurslar",
    "courses.free": "Bepul",
    "courses.buy": "Sotib olish",
    "courses.videos": "ta video",
    "courses.purchased": "Sotib olingan",
    "courses.watch": "Ko'rish",
    "common.loading": "Yuklanmoqda...",
    "common.error": "Xatolik",
    "common.success": "Muvaffaqiyat",
    "common.cancel": "Bekor qilish",
    "common.confirm": "Tasdiqlash",
    "common.back": "Orqaga",
    "common.km": "km",
    "payment.title": "Kredit sotib olish",
    "payment.keys": "kredit",
    "payment.som": "so'm",
    "payment.card_number": "Karta raqami",
    "payment.transfer_to": "ga o'tkazing",
    "payment.send_receipt": "Chekni yuborish",
    "payment.uploading": "Yuklanmoqda...",
    "payment.receipt_sent": "Chek yuborildi. Admin tasdiqlashini kuting.",
    "payment.modal_title": "To'lov",
    "payment.login_required": "Tizimga kiring",
    "payment.connection_error": "Ulanishda xatolik. Qayta urinib ko'ring.",
    "payment.retry": "Qayta urinish",
    "partial.title": "Qoldiq to'lov mavjud",
    "partial.sub": "so'm — yangi chek yuboring",
    "partial.pay_btn": "To'lash",
    "profile.fill_all_fields": "Barcha maydonlarni to'ldiring",
    "profile.photo_permission_title": "Ruxsat kerak",
    "profile.photo_permission_desc": "Rasmlar kutubxonasiga ruxsat bering",
    "profile.photo_upload_error": "Rasm yuklanmadi",
    "profile.admin_login_success": "Admin sifatida kirdingiz",
    "profile.admin_wrong_password": "Parol noto'g'ri",
    "profile.logout_confirm": "Tizimdan chiqmoqchimisiz?",
    "profile.default_user": "Foydalanuvchi",
    "profile.admin_password_placeholder": "Admin paroli",
    "profile.admin_enter": "Kirish",
    "profile.admin_enter_password": "Parolni kiriting:",
    "home.loading": "Yuklanmoqda...",
  },
  ru: {
    "app.name": "FitBoom",
    "nav.home": "Главная",
    "nav.gyms": "Залы",
    "nav.map": "Карта",
    "nav.bookings": "Бронь",
    "nav.profile": "Профиль",
    "nav.scanner": "Сканер",
    "nav.classes": "Видео уроки",
    "auth.title": "Добро пожаловать в FitBoom",
    "auth.subtitle": "Управляйте своей спортивной жизнью",
    "auth.phone_label": "Номер телефона",
    "auth.phone_placeholder": "+998901234567",
    "auth.send_code": "Отправить код",
    "auth.sending": "Отправляется...",
    "auth.code_label": "Код подтверждения",
    "auth.code_placeholder": "6-значный код",
    "auth.verify": "Подтвердить",
    "auth.verifying": "Проверяется...",
    "auth.code_sent": "Код отправлен",
    "auth.resend": "Отправить снова",
    "auth.back": "Назад",
    "profile.complete_title": "Заполните профиль",
    "profile.complete_subtitle": "Введите данные для продолжения",
    "profile.name": "Имя",
    "profile.name_placeholder": "Введите имя",
    "profile.age": "Возраст",
    "profile.age_placeholder": "Введите возраст",
    "profile.gender": "Пол",
    "profile.male": "Мужчина",
    "profile.female": "Женщина",
    "profile.save": "Сохранить",
    "profile.saving": "Сохраняется...",
    "profile.title": "Профиль",
    "profile.credits": "кредит",
    "profile.edit": "Редактировать",
    "profile.logout": "Выйти",
    "profile.admin": "Панель админа",
    "profile.gym_owner": "Панель владельца",
    "profile.settings": "Настройки",
    "profile.language": "Язык",
    "profile.expires": "Истекает",
    "profile.days_left": "дней осталось",
    "profile.credits_title": "Баланс кредитов",
    "profile.credits_count": "кредит",
    "profile.topup": "Пополнить",
    "profile.expired_message": "Срок истёк! Обновите",
    "profile.renew": "Обновить",
    "profile.expiring_soon": "Внимание:",
    "profile.credit_history": "История кредитов",
    "profile.topup_history": "История пополнений",
    "profile.no_credit_history": "История кредитов пуста",
    "profile.no_topup_history": "История пополнений пуста",
    "profile.expired_badge": "Срок истёк!",
    "home.welcome": "Добро пожаловать",
    "home.balance": "Баланс кредитов",
    "home.topup": "Пополнить",
    "home.near_gyms": "Ближайшие залы к вам",
    "home.my_bookings": "Мои бронирования",
    "home.no_bookings": "Нет активных бронирований",
    "home.view_all": "Смотреть все",
    "home.upcoming": "Предстоящие брони",
    "home.subtitle": "Управляйте своей спортивной жизнью",
    "home.sorted_by_distance": "Отсортировано по расстоянию",
    "home.days_left": "дней осталось",
    "home.expired": "Срок истёк",
    "home.renew": "Обновить",
    "home.scanner_desc": "Скоро эта функция будет доступна. Вы сможете войти в зал через QR-код.",
    "gyms.title": "Спортивные залы",
    "gyms.search": "Поиск зала...",
    "gyms.all": "Все",
    "gyms.no_results": "Залы не найдены",
    "gyms.credits": "кредит",
    "gym.book": "Забронировать",
    "gym.book_now": "Забронировать сейчас",
    "gym.slots": "Временные слоты",
    "gym.no_slots": "Сегодня нет временных слотов",
    "gym.select_slot": "Выберите время",
    "gym.select_date": "Выберите дату",
    "gym.confirm_booking": "Подтвердить бронь",
    "gym.credits_needed": "кредит нужен",
    "gym.not_enough": "Недостаточно кредитов",
    "gym.booked": "Забронировано!",
    "gym.facilities": "Удобства",
    "gym.hours": "Рабочие часы",
    "gym.address": "Адрес",
    "gym.rating": "Рейтинг",
    "gym.open_maps": "Открыть на карте",
    "map.title": "Карта залов",
    "map.locate_me": "Моё местоположение",
    "bookings.title": "Бронирования",
    "bookings.upcoming": "Предстоящие",
    "bookings.past": "Прошедшие",
    "bookings.no_upcoming": "Нет предстоящих броней",
    "bookings.no_past": "Нет прошедших броней",
    "bookings.cancel": "Отменить",
    "bookings.show_qr": "Показать QR",
    "bookings.cancelled": "Отменено",
    "bookings.credits_returned": "Кредит возвращён",
    "bookings.status_pending": "В ожидании",
    "bookings.status_completed": "Посещено",
    "bookings.status_missed": "Не явился",
    "bookings.status_cancelled": "Отменено",
    "bookings.status_unknown": "Неизвестно",
    "bookings.tab_upcoming": "Предстоящие",
    "bookings.tab_past": "Прошедшие",
    "bookings.empty_upcoming": "Пока нет активных бронирований",
    "bookings.empty_past": "Нет прошедших бронирований",
    "bookings.gym_default": "Спортзал",
    "bookings.scanner_btn": "Сканер",
    "bookings.cancel_confirm": "Отменить бронирование?",
    "bookings.cancel_no": "Нет",
    "bookings.cancel_yes": "Да, отменить",
    "bookings.within_2h_warning": "Менее 2 часов до начала — кредиты не вернут при отмене",
    "bookings.cancel_2h_title": "⚠️ Внимание!",
    "bookings.cancel_2h_msg": "До начала менее 2 часов. При отмене кредиты не вернут. Всё равно отменить?",
    "bookings.cancel_stay": "Нет, оставить",
    "bookings.cancel_do": "Да, отменить",
    "bookings.cancel_success": "Успешно!",
    "bookings.cancel_no_refund": "Бронь отменена. Кредиты не возвращены (менее 2 часов до начала).",
    "bookings.cancel_base_msg": "Бронь отменена.",
    "bookings.cancel_refund_suffix": " кредитов возвращено.",
    "bookings.error_no_id": "ID бронирования не найден",
    "bookings.session_expired": "Сессия истекла. Войдите заново.",
    "bookings.cancel_error": "Ошибка при отмене бронирования",
    "scanner.title": "QR Сканер",
    "scanner.desc": "Сканируйте QR-код зала",
    "scanner.scanning": "Сканирование...",
    "scanner.success": "Вход подтверждён!",
    "scanner.permission_title": "Нужен доступ к камере",
    "scanner.permission_desc": "Разрешите доступ к камере для сканирования QR",
    "scanner.permission_denied": "Доступ к камере запрещён. Разрешите его в настройках устройства.",
    "scanner.grant": "Разрешить",
    "scanner.open_settings": "Открыть настройки",
    "scanner.ticket_title": "ВХОД ПОДТВЕРЖДЁН",
    "scanner.time_label": "Время",
    "scanner.date_label": "Дата",
    "scanner.show_admin": "Покажите этот экран администратору",
    "scanner.rescan": "Сканировать снова",
    "scanner.back_bookings": "К бронированиям",
    "scanner.checking": "Проверяется...",
    "scanner.hint": "У каждого зала есть QR-код у входа. Отсканируйте его.",
    "scanner.frame_hint": "Наведите камеру на QR-код у входа в зал",
    "scanner.not_fitboom_qr": "Это не QR-код FitBoom",
    "scanner.not_gym_qr": "Это не QR-код зала FitBoom",
    "scanner.error_generic": "Произошла ошибка",
    "scanner.welcome_default": "добро пожаловать!",
    "courses.title": "Видео Курсы",
    "courses.free": "Бесплатно",
    "courses.buy": "Купить",
    "courses.videos": "видео",
    "courses.purchased": "Куплено",
    "courses.watch": "Смотреть",
    "common.loading": "Загрузка...",
    "common.error": "Ошибка",
    "common.success": "Успешно",
    "common.cancel": "Отмена",
    "common.confirm": "Подтвердить",
    "common.back": "Назад",
    "common.km": "км",
    "payment.title": "Купить кредиты",
    "payment.keys": "кредит",
    "payment.som": "сум",
    "payment.card_number": "Номер карты",
    "payment.transfer_to": "переведите на",
    "payment.send_receipt": "Отправить чек",
    "payment.uploading": "Загрузка...",
    "payment.receipt_sent": "Чек отправлен. Ожидайте подтверждения.",
    "payment.modal_title": "Оплата",
    "payment.login_required": "Войдите в систему",
    "payment.connection_error": "Ошибка подключения. Попробуйте снова.",
    "payment.retry": "Попробовать снова",
    "partial.title": "Есть остаток оплаты",
    "partial.sub": "сум — отправьте новый чек",
    "partial.pay_btn": "Оплатить",
    "profile.fill_all_fields": "Заполните все поля",
    "profile.photo_permission_title": "Нужно разрешение",
    "profile.photo_permission_desc": "Разрешите доступ к галерее",
    "profile.photo_upload_error": "Не удалось загрузить фото",
    "profile.admin_login_success": "Вы вошли как администратор",
    "profile.admin_wrong_password": "Неверный пароль",
    "profile.logout_confirm": "Выйти из системы?",
    "profile.default_user": "Пользователь",
    "profile.admin_password_placeholder": "Пароль администратора",
    "profile.admin_enter": "Войти",
    "profile.admin_enter_password": "Введите пароль:",
    "home.loading": "Загрузка...",
  },
  en: {
    "app.name": "FitBoom",
    "nav.home": "Home",
    "nav.gyms": "Gyms",
    "nav.map": "Map",
    "nav.bookings": "Bookings",
    "nav.profile": "Profile",
    "nav.scanner": "Scanner",
    "nav.classes": "Video Classes",
    "auth.title": "Welcome to FitBoom",
    "auth.subtitle": "Manage your fitness life",
    "auth.phone_label": "Phone Number",
    "auth.phone_placeholder": "+998901234567",
    "auth.send_code": "Send Code",
    "auth.sending": "Sending...",
    "auth.code_label": "Verification Code",
    "auth.code_placeholder": "6-digit code",
    "auth.verify": "Verify",
    "auth.verifying": "Verifying...",
    "auth.code_sent": "Code Sent",
    "auth.resend": "Resend",
    "auth.back": "Back",
    "profile.complete_title": "Complete Profile",
    "profile.complete_subtitle": "Enter your details to continue",
    "profile.name": "Name",
    "profile.name_placeholder": "Enter your name",
    "profile.age": "Age",
    "profile.age_placeholder": "Enter your age",
    "profile.gender": "Gender",
    "profile.male": "Male",
    "profile.female": "Female",
    "profile.save": "Save",
    "profile.saving": "Saving...",
    "profile.title": "Profile",
    "profile.credits": "credits",
    "profile.edit": "Edit",
    "profile.logout": "Logout",
    "profile.admin": "Admin Panel",
    "profile.gym_owner": "Gym Owner Panel",
    "profile.settings": "Settings",
    "profile.language": "Language",
    "profile.expires": "Expires",
    "profile.days_left": "days left",
    "profile.credits_title": "Credit Balance",
    "profile.credits_count": "credit",
    "profile.topup": "Top Up",
    "profile.expired_message": "Expired! Please renew",
    "profile.renew": "Renew",
    "profile.expiring_soon": "Warning:",
    "profile.credit_history": "Credit History",
    "profile.topup_history": "Topup History",
    "profile.no_credit_history": "No credit history",
    "profile.no_topup_history": "No topup history",
    "profile.expired_badge": "Expired!",
    "home.welcome": "Welcome",
    "home.balance": "Credit Balance",
    "home.topup": "Top Up",
    "home.near_gyms": "Nearest Gyms To You",
    "home.my_bookings": "My Bookings",
    "home.no_bookings": "No active bookings",
    "home.view_all": "View All",
    "home.upcoming": "Upcoming Bookings",
    "home.subtitle": "Manage your fitness life",
    "home.sorted_by_distance": "Sorted by distance",
    "home.days_left": "days left",
    "home.expired": "Expired",
    "home.renew": "Renew",
    "home.scanner_desc": "This feature is coming soon. You will be able to enter the gym by scanning a QR code.",
    "gyms.title": "Gyms",
    "gyms.search": "Search gym...",
    "gyms.all": "All",
    "gyms.no_results": "No gyms found",
    "gyms.credits": "credit",
    "gym.book": "Book",
    "gym.book_now": "Book Now",
    "gym.slots": "Time Slots",
    "gym.no_slots": "No slots for today",
    "gym.select_slot": "Select time",
    "gym.select_date": "Select date",
    "gym.confirm_booking": "Confirm Booking",
    "gym.credits_needed": "credit needed",
    "gym.not_enough": "Not enough credits",
    "gym.booked": "Booked!",
    "gym.facilities": "Facilities",
    "gym.hours": "Working Hours",
    "gym.address": "Address",
    "gym.rating": "Rating",
    "gym.open_maps": "Open in Maps",
    "map.title": "Gym Map",
    "map.locate_me": "My Location",
    "bookings.title": "Bookings",
    "bookings.upcoming": "Upcoming",
    "bookings.past": "Past",
    "bookings.no_upcoming": "No upcoming bookings",
    "bookings.no_past": "No past bookings",
    "bookings.cancel": "Cancel",
    "bookings.show_qr": "Show QR Code",
    "bookings.cancelled": "Cancelled",
    "bookings.credits_returned": "Credit returned",
    "bookings.status_pending": "Pending",
    "bookings.status_completed": "Visited",
    "bookings.status_missed": "Missed",
    "bookings.status_cancelled": "Cancelled",
    "bookings.status_unknown": "Unknown",
    "bookings.tab_upcoming": "Upcoming",
    "bookings.tab_past": "Past",
    "bookings.empty_upcoming": "No active bookings yet",
    "bookings.empty_past": "No past bookings",
    "bookings.gym_default": "Gym",
    "bookings.scanner_btn": "Scanner",
    "bookings.cancel_confirm": "Cancel booking?",
    "bookings.cancel_no": "No",
    "bookings.cancel_yes": "Yes, cancel",
    "bookings.within_2h_warning": "Less than 2h to start — credits won't be refunded on cancel",
    "bookings.cancel_2h_title": "⚠️ Warning!",
    "bookings.cancel_2h_msg": "Less than 2 hours to start. Credits won't be refunded. Still cancel?",
    "bookings.cancel_stay": "No, keep it",
    "bookings.cancel_do": "Yes, cancel",
    "bookings.cancel_success": "Success!",
    "bookings.cancel_no_refund": "Booking cancelled. Credits not refunded (less than 2 hours to start).",
    "bookings.cancel_base_msg": "Booking cancelled.",
    "bookings.cancel_refund_suffix": " credits returned.",
    "bookings.error_no_id": "Booking ID not found",
    "bookings.session_expired": "Session expired. Please login again.",
    "bookings.cancel_error": "Error cancelling booking",
    "scanner.title": "QR Scanner",
    "scanner.desc": "Scan the gym QR code",
    "scanner.scanning": "Scanning...",
    "scanner.success": "Access confirmed!",
    "scanner.permission_title": "Camera Permission Needed",
    "scanner.permission_desc": "Grant camera access to scan QR codes",
    "scanner.permission_denied": "Camera access denied. Enable it in device settings.",
    "scanner.grant": "Grant",
    "scanner.open_settings": "Open Settings",
    "scanner.ticket_title": "ACCESS CONFIRMED",
    "scanner.time_label": "Time",
    "scanner.date_label": "Date",
    "scanner.show_admin": "Show this screen to the admin",
    "scanner.rescan": "Scan Again",
    "scanner.back_bookings": "Back to Bookings",
    "scanner.checking": "Checking...",
    "scanner.hint": "Each gym has a QR code at the entrance. Scan it.",
    "scanner.frame_hint": "Place the gym QR code inside the frame",
    "scanner.not_fitboom_qr": "This is not a FitBoom QR code",
    "scanner.not_gym_qr": "This is not a FitBoom gym QR code",
    "scanner.error_generic": "An error occurred",
    "scanner.welcome_default": "welcome!",
    "courses.title": "Video Courses",
    "courses.free": "Free",
    "courses.buy": "Buy",
    "courses.videos": "videos",
    "courses.purchased": "Purchased",
    "courses.watch": "Watch",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.back": "Back",
    "common.km": "km",
    "payment.title": "Buy Credits",
    "payment.keys": "credits",
    "payment.som": "UZS",
    "payment.card_number": "Card Number",
    "payment.transfer_to": "transfer to",
    "payment.send_receipt": "Send Receipt",
    "payment.uploading": "Uploading...",
    "payment.receipt_sent": "Receipt sent. Awaiting admin confirmation.",
    "payment.modal_title": "Payment",
    "payment.login_required": "Please log in",
    "payment.connection_error": "Connection error. Please try again.",
    "payment.retry": "Retry",
    "partial.title": "Partial payment pending",
    "partial.sub": "UZS — send a new receipt",
    "partial.pay_btn": "Pay Now",
    "profile.fill_all_fields": "Please fill in all fields",
    "profile.photo_permission_title": "Permission Required",
    "profile.photo_permission_desc": "Please allow access to your photo library",
    "profile.photo_upload_error": "Failed to upload photo",
    "profile.admin_login_success": "Logged in as admin",
    "profile.admin_wrong_password": "Wrong password",
    "profile.logout_confirm": "Sign out of the app?",
    "profile.default_user": "User",
    "profile.admin_password_placeholder": "Admin password",
    "profile.admin_enter": "Enter",
    "profile.admin_enter_password": "Enter password:",
    "home.loading": "Loading...",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "uz",
  setLanguage: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("uz");

  useEffect(() => {
    AsyncStorage.getItem("language").then((saved) => {
      if (saved === "uz" || saved === "ru" || saved === "en") {
        setLanguageState(saved);
      }
    });
  }, []);

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    await AsyncStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations["uz"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
