// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fitboom-home/BoldEnergy.tsx": () => import("../components/mockups/fitboom-home/BoldEnergy.tsx"),
  "./components/mockups/fitboom-home/CleanLight.tsx": () => import("../components/mockups/fitboom-home/CleanLight.tsx"),
  "./components/mockups/fitboom-home/PremiumDark.tsx": () => import("../components/mockups/fitboom-home/PremiumDark.tsx")
};
